language: node_js
cache: npm
node_js: "10.15.3"
before_install:
  - npm i
before_script:
  - psql -c "create database $DB_NAME;" -U postgres
services: postgresql
addons:
  postgresql: "9.4"
jobs:
  include:
    - stage: test
      script:
        - export NODE_ENV=test DB_NAME=test
        - npm run knex:migrate
        - npm run knex:seed
        - npm run test:travis
