sudo: true
cache: npm
language: node_js
node_js: "10.15.3"
before_install:
  - echo "downgrading postgres to 9.6"
  - sudo apt-get --yes remove postgresql\*
  - sudo apt-get install -y postgresql-11 postgresql-client-11
  - sudo cp /etc/postgresql/{9.6,11}/main/pg_hba.conf
  - sudo service postgresql restart 11
  - echo "installing packages"
  - npm i
before_script:
  - export NODE_ENV=test DB_NAME=test PAYLOAD_PRIVATE_KEY_PATH=~/jwt_test_key.pem
  - echo "configuring test database"
  - psql -c "CREATE DATABASE $DB_NAME;" -U postgres
  - psql -c 'CREATE ROLE travis SUPERUSER LOGIN CREATEDB;' -U postgres
services: postgresql
addons:
  postgresql: "11.3"
jobs:
  include:
    - stage: lint
      script:
        - npm run lint
    - stage: test
      script:
        - echo "generating test private key"
        - openssl genrsa -out ~/jwt_test_key.pem 2048
        - npm run knex:migrate
        - npm run test:travis
