language: node_js
cache: npm
node_js: "10.15.3"
before_install: npm i
services: postgresql
addons:
  postgresql: "11"
jobs:
  include:
    - stage: test
      env:
        - NODE_ENV=test
        - DB_NAME=test
      script:
        - psql -c "create database $DB_NAME;" -U postgres
        - npm run knex:migrate
        - npm run knex:seed
        - npm run test:travis
