version: "3.8"

services:
  db:
    image: postgres:11-alpine
    container_name: pg-api-db
    environment:
      POSTGRES_USER: "princeton"
      POSTGRES_DB: "groundwater"
      POSTGRES_PASSWORD: "princeton"
    ports:
      - "5432:5432"
    

