version: 2.1
orbs:
  coveralls: coveralls/coveralls@1.0.6
jobs:
  test:
    docker:
      - image: circleci/node:lts
      - image: circleci/postgres:11.4
    steps:
      - checkout
      - run: npm ci
      - run: npm run knex:migrate
      - run: npm run test:ci
      - coveralls/upload
workflows:
  testing:
    jobs:
      - test
